### PR TITLE
Fixes issue that commenting only works for visible lines

### LINKED ISSUE #3: Commenting feature only comments visible lines
The comment / uncomment only processes visible lines.
To demonstrate:
- open a larger pkgdef file and make sure that the editor window has a size where not all lines are visible
- press Ctrl-A to select all lines
- press Ctrl-K-C to comment the contents
- scroll to the part of the editor that was not visible
- you will see that these lines were not commented out.
The problem is caused by the fact that GetTextViewLinesIntersectingSpan() only returns visible lines

### PR DESCRIPTION
**Pull request by RobertvanderHulst**
Fixes #3

### CODE REVIEW

File: src/Commands/Commenting.cs [hunk 1]
```diff
@@ -35,28 +32,55 @@ private static CommandProgression Execute(Action<DocumentView> action)
...
+            int end = doc.TextView.Selection.End.Position.Position;
+            var editsession = doc.TextBuffer.CreateEdit();
+            while (start < end)
             {
-                doc.TextBuffer.Insert(line.Start.Position, Constants.CommentChars[0]);
+                var line = snapshot.GetLineFromPosition(start);
+                editsession.Insert(line.Start.Position, Constants.CommentChars[0] + " ");
+                start = line.EndIncludingLineBreak.Position;
             }
+            editsession.Apply();
```
Comment (madskristensen) [inline src/Commands/Commenting.cs]: The `editsession` must always be disposed after use. It can be done by wrapping `using` around it. Same for the `Uncomment` method

Comment (RobertvanderHulst) [reply src/Commands/Commenting.cs]: Done

**Comment by madskristensen** [comment]
Thanks so much!
